In [4]:
#Assignment
# %pip install numpy
import numpy as np

#Q3: Create a 4×5 numpy array of all True’s.
q3 = np.ones((4, 5), dtype = bool)
q3

#OR
# q33=np.full((4,5),True)
# q33

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
# Q4: Create an array of integers from 10 to 50 with with step of 3. Save the array in a. Replace all even numbers in a with -1.
a=np.arange(10,20,3)
a
a[:]=-1


In [8]:
# Q5: Create an one-dimensional array which includes odd numbers from 1 to 20.
q5=np.arange(1,20,2)
q5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
# a: Change all numbers divisible by 3 into 0.

q5[(q5 %3 == 0) & (q5>=3)]


array([ 3,  9, 15])

In [10]:
# b: Change the array into a 2x5 matrix.
b=q5.reshape(2,5)
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [12]:
# c: Convert all numbers of the third column into zero. Q6:
b[:,2]=0
b

array([[ 1,  3,  0,  7,  9],
       [11, 13,  0, 17, 19]])

In [14]:
#a: Create an one-dimensional array, b1, which includes 9 numbers evenly spaced over 1.5 to 3.
b1=np.linspace(1.5,3,9)
b1

array([1.5   , 1.6875, 1.875 , 2.0625, 2.25  , 2.4375, 2.625 , 2.8125,
       3.    ])

In [15]:
# b: Create a 3x3 matrix, b2, which includes random numbers from Gaussian distribution with mean = 1, and sd = 0.75, seed = 1234.
np.random.seed(1234)
b2 = np.random.normal(1, 0.75, (3, 3))
b2


array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

In [18]:
# c: Calculate the determinant of b2.
c=np.linalg.det(b2)
c

-1.0770051050177027

In [20]:
# d: What is the transpose of matrix b2?
b2.T

array([[1.35357637, 0.76551108, 1.64469131],
       [0.10676823, 0.45955845, 0.52260737],
       [2.07453023, 1.66537221, 1.01177228]])

In [25]:
# e: Convert b1 into a 3x3 matrix.
b1=b1.reshape(3,3)
b1

array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

In [26]:
# f: Calculate summation of b1 and b2.
f=b1+b2
f

array([[2.85357637, 1.79426823, 3.94953023],
       [2.82801108, 2.70955845, 4.10287221],
       [4.26969131, 3.33510737, 4.01177228]])

In [27]:
# g: Calculate matrix multiplication of b1 and b2.

np.dot(b1,b2)


array([[ 6.40596071,  1.91554605,  7.81918396],
       [ 8.52308626,  2.52807145, 10.49200098],
       [10.64021182,  3.14059686, 13.16481801]])

In [36]:
# h: Call all numbers of b2 which are greater than mean of b2.
b2[b2>(np.mean(b2))]
# h=np.mean(b2)
# h
# b2[b2>h]

array([1.35357637, 2.07453023, 1.66537221, 1.64469131])

In [53]:
# i: Scale matrix b2 using min-max scaling method. End of Code
i1=np.min(b2)
i1=np.array([i1])

i2=np.max(b2)
i2=np.array([i2])

np.concatenate((i1, i2), axis = 0)

array([0.10676823, 2.07453023])